const menu=document.querySelector(".menu");
const links=document.querySelector(".links");
menu?.addEventListener("click",()=>links.classList.toggle("open"));
document.querySelectorAll(".links>a").forEach(a=>a.addEventListener("click",()=>links.classList.remove("open")));

const translations={
 en:{
  "nav.work":"Work","nav.services":"Services","nav.talk":"Let's talk ↗",
  "eyebrow.hero":"INDEPENDENT WEB DESIGN · SOUTH FLORIDA",
  "hero.title":"Your vision.<br>Your website.<br><em>Made to matter.</em>",
  "hero.lead":"A polished home for your business. A personal brand that feels like you. A gift they’ll open again and again.",
  "hero.copy":"I’m Rolph. I turn your ideas into websites with personality and purpose.",
  "hero.work":"Explore my work ↗","hero.plan":"Plan a project",
  "ticker.business":"Business websites","ticker.personal":"Personal sites","ticker.gifts":"Digital gifts","ticker.small":"Built around your story. Designed for phones and desktops. English · Français · Kreyòl",
  "work.eye":"FEATURED WORK / 01","work.title":"A clear look.<br>A strong first impression.","work.desc":"A look at what your idea could become. Explore this website concept for a local detailing business.","work.explore":"Explore the packages ↗","work.meta":"Gloss Auto Detailing<br>Business website · Portfolio concept",
  "services.eye":"WHAT I CAN CREATE","services.title":"Small business.<br>Big occasion.<br>Your next idea.","services.desc":"We’ll agree on the pages, features, price, and timing before your project begins.",
  "c1.label":"01 / FOR YOUR BUSINESS","c1.title":"Give your business a home online.","c1.p":"Clear, easy-to-browse websites for detailers, barbers, and other local service businesses.","c1.list":"<li>Services and pricing sections</li><li>Work galleries and business details</li><li>Your booking link or contact options</li>",
  "c2.label":"02 / FOR YOUR STORY","c2.title":"Show the world what you do.","c2.p":"A personal website that puts your work and personality in one place.","c2.list":"<li>Portfolio and project showcases</li><li>About you and your services</li><li>Social links and ways to connect</li>",
  "c3.label":"03 / FOR SOMEONE SPECIAL","c3.title":"Make a moment they can revisit.","c3.p":"A thoughtful digital gift for an anniversary, birthday, or someone you love.","c3.list":"<li>Photo memories and stories</li><li>Personal letters and messages</li><li>A design made for the occasion</li>",
  "about.eye":"THE PERSON BEHIND THE PIXELS","about.title":"Hey, I’m Rolph.<br><em>Let’s make it yours.</em>","about.p1":"I started making websites to bring ideas to life, including a personal gift for someone special. Now I’m building Rolph Studio to help people put their own stories and businesses online.","about.p2":"You bring the idea, photos, and details. I help shape them into a website that’s clear, personal, and easy to use.","about.lang":"Let’s connect in English, French, or Haitian Creole.",
  "steps.eye":"HOW WE’LL WORK TOGETHER","steps.title":"From “I have an idea”<br>to “that’s my website.”","s1.label":"THE CONVERSATION","s1.title":"Tell me what you’re imagining.","s1.p":"We talk about your audience, the goal of your site, and the content you have.","s2.label":"THE FIRST LOOK","s2.title":"See your idea take shape.","s2.p":"I put together a design for you to review. We refine it within the scope we agreed on.","s3.label":"THE HANDOFF","s3.title":"Get ready to share it.","s3.p":"We check the final details and agree on hosting, your domain, and how future updates will work.",
  "faq.eye":"A FEW THINGS TO KNOW","faq.title":"Before we<br>get started.","q1":"How much does a website cost?","a1":"Every project is different. We’ll agree on the scope, pages, features, price, and timing before work begins.","q2":"What do I need to provide?","a2":"Your idea, business or project details, text, photos, links, and anything else you want included.","q3":"Can you connect my booking page?","a3":"Yes. Existing booking and contact links can be built into your website.","q4":"Can I request changes later?","a4":"We can discuss future updates and how you want the website maintained after handoff.",
  "contact.eye":"YOUR IDEA STARTS HERE","contact.title":"Let’s make<br><em>something yours.</em>","contact.p":"Tell me what you’re creating, who it’s for, and when you’d like it ready.","contact.ready":"Ready to start a project?","contact.reply":"Tell me what you’re creating and I’ll get back to you.","contact.email":"Email me ↗","contact.call":"Call me ↗","contact.text":"Text me ↗","footer":"© 2026 Rolph Studio · Your vision. Your website.","footer.work":"Explore the work ↗"
 },
 fr:{
  "nav.work":"Projets","nav.services":"Services","nav.talk":"Parlons-en ↗","eyebrow.hero":"WEB DESIGN INDÉPENDANT · SUD DE LA FLORIDE","hero.title":"Votre vision.<br>Votre site web.<br><em>Conçu pour compter.</em>","hero.lead":"Un site soigné pour votre entreprise. Une marque personnelle qui vous ressemble. Un cadeau qu’on aura envie de revoir encore et encore.","hero.copy":"Moi, c’est Rolph. Je transforme vos idées en sites web avec du caractère et un vrai objectif.","hero.work":"Voir mes projets ↗","hero.plan":"Planifier un projet","ticker.business":"Sites pour entreprises","ticker.personal":"Sites personnels","ticker.gifts":"Cadeaux numériques","ticker.small":"Conçu autour de votre histoire. Adapté aux téléphones et ordinateurs. English · Français · Kreyòl",
  "work.eye":"PROJET À LA UNE / 01","work.title":"Un style clair.<br>Une première impression forte.","work.desc":"Découvrez ce que votre idée pourrait devenir avec ce concept de site pour une entreprise locale de detailing.","work.explore":"Voir les forfaits ↗","work.meta":"Gloss Auto Detailing<br>Site d’entreprise · Concept portfolio",
  "services.eye":"CE QUE JE PEUX CRÉER","services.title":"Petite entreprise.<br>Grande occasion.<br>Votre prochaine idée.","services.desc":"Nous nous mettons d’accord sur les pages, les fonctionnalités, le prix et le délai avant de commencer.",
  "c1.label":"01 / POUR VOTRE ENTREPRISE","c1.title":"Donnez à votre entreprise sa place en ligne.","c1.p":"Des sites clairs et faciles à parcourir pour detailers, barbiers et autres services locaux.","c1.list":"<li>Services et tarifs</li><li>Galeries et informations de l’entreprise</li><li>Lien de réservation ou moyens de contact</li>","c2.label":"02 / POUR VOTRE HISTOIRE","c2.title":"Montrez au monde ce que vous faites.","c2.p":"Un site personnel qui rassemble votre travail et votre personnalité.","c2.list":"<li>Portfolio et présentation de projets</li><li>À propos de vous et de vos services</li><li>Réseaux sociaux et moyens de vous contacter</li>","c3.label":"03 / POUR QUELQU’UN DE SPÉCIAL","c3.title":"Créez un moment qu’on peut revivre.","c3.p":"Un cadeau numérique attentionné pour un anniversaire, une occasion spéciale ou une personne que vous aimez.","c3.list":"<li>Photos, souvenirs et histoires</li><li>Lettres et messages personnels</li><li>Un design créé pour l’occasion</li>",
  "about.eye":"DERRIÈRE LES PIXELS","about.title":"Salut, moi c’est Rolph.<br><em>Créons quelque chose qui vous ressemble.</em>","about.p1":"J’ai commencé à créer des sites pour donner vie à des idées, notamment un cadeau personnel pour quelqu’un de spécial. Aujourd’hui, je développe Rolph Studio pour aider les gens à mettre leurs histoires et leurs entreprises en ligne.","about.p2":"Vous apportez l’idée, les photos et les détails. Je vous aide à en faire un site clair, personnel et facile à utiliser.","about.lang":"Parlons en anglais, en français ou en créole haïtien.",
  "steps.eye":"COMMENT NOUS TRAVAILLERONS ENSEMBLE","steps.title":"De « j’ai une idée »<br>à « c’est mon site ».","s1.label":"LA CONVERSATION","s1.title":"Dites-moi ce que vous imaginez.","s1.p":"Nous parlons de votre public, de l’objectif du site et du contenu dont vous disposez.","s2.label":"LE PREMIER APERÇU","s2.title":"Voyez votre idée prendre forme.","s2.p":"Je prépare un design à examiner avec vous. Nous l’affinons selon ce qui a été convenu.","s3.label":"LA LIVRAISON","s3.title":"Préparez-vous à le partager.","s3.p":"Nous vérifions les derniers détails et convenons de l’hébergement, du domaine et des futures mises à jour.",
  "faq.eye":"QUELQUES POINTS À SAVOIR","faq.title":"Avant de<br>commencer.","q1":"Combien coûte un site web ?","a1":"Chaque projet est différent. Nous convenons du périmètre, des pages, des fonctionnalités, du prix et du délai avant de commencer.","q2":"Que dois-je fournir ?","a2":"Votre idée, les informations sur votre entreprise ou projet, les textes, photos, liens et tout ce que vous souhaitez inclure.","q3":"Pouvez-vous connecter ma page de réservation ?","a3":"Oui. Vos liens de réservation et de contact existants peuvent être intégrés au site.","q4":"Puis-je demander des modifications plus tard ?","a4":"Nous pouvons discuter des futures mises à jour et de la maintenance du site après sa livraison.",
  "contact.eye":"VOTRE IDÉE COMMENCE ICI","contact.title":"Créons<br><em>quelque chose à vous.</em>","contact.p":"Dites-moi ce que vous créez, pour qui, et quand vous aimeriez que ce soit prêt.","contact.ready":"Prêt à lancer un projet ?","contact.reply":"Expliquez-moi ce que vous créez et je vous répondrai.","contact.email":"M’écrire ↗","contact.call":"M’appeler ↗","contact.text":"M’envoyer un SMS ↗","footer":"© 2026 Rolph Studio · Votre vision. Votre site web.","footer.work":"Voir les projets ↗"
 },
 ht:{
  "nav.work":"Pwojè","nav.services":"Sèvis","nav.talk":"Ann pale ↗","eyebrow.hero":"WEB DESIGN ENDEPANDAN · SID FLORIDA","hero.title":"Vizyon pa w.<br>Sit entènèt pa w.<br><em>Fèt pou l gen enpòtans.</em>","hero.lead":"Yon bèl espas sou entènèt pou biznis ou. Yon mak pèsonèl ki sanble avè w. Yon kado yo ka retounen gade ankò e ankò.","hero.copy":"Mwen se Rolph. Mwen transfòme lide ou yo an sit entènèt ki gen pèsonalite ak objektif.","hero.work":"Gade pwojè mwen yo ↗","hero.plan":"Planifye yon pwojè","ticker.business":"Sit pou biznis","ticker.personal":"Sit pèsonèl","ticker.gifts":"Kado dijital","ticker.small":"Bati sou istwa pa w. Fèt pou telefòn ak òdinatè. English · Français · Kreyòl",
  "work.eye":"PWOJÈ NOU METE DEVAN / 01","work.title":"Yon aparans klè.<br>Yon premye enpresyon solid.","work.desc":"Gade sa lide pa w la ka tounen. Dekouvri konsèp sit sa a pou yon biznis detailing lokal.","work.explore":"Gade pakè yo ↗","work.meta":"Gloss Auto Detailing<br>Sit biznis · Konsèp portfolio",
  "services.eye":"SA MWEN KA KREYE","services.title":"Ti biznis.<br>Gwo okazyon.<br>Pwochen lide pa w.","services.desc":"N ap dakò sou paj yo, fonksyon yo, pri a ak delè a anvan pwojè a kòmanse.",
  "c1.label":"01 / POU BIZNIS OU","c1.title":"Bay biznis ou yon kay sou entènèt.","c1.p":"Sit ki klè e fasil pou navige pou detailers, barbers ak lòt sèvis lokal.","c1.list":"<li>Sèvis ak pri</li><li>Galri travay ak enfòmasyon biznis</li><li>Lyen rezèvasyon oswa fason pou kontakte w</li>","c2.label":"02 / POU ISTWA PA W","c2.title":"Montre moun sa w ap fè.","c2.p":"Yon sit pèsonèl ki mete travay ou ak pèsonalite ou nan yon sèl kote.","c2.list":"<li>Portfolio ak pwojè ou yo</li><li>Enfòmasyon sou ou ak sèvis ou</li><li>Rezo sosyal ak fason pou kontakte w</li>","c3.label":"03 / POU YON MOUN ESPESYAL","c3.title":"Kreye yon moman yo ka reviv.","c3.p":"Yon kado dijital ki gen sans pou anivèsè, yon okazyon espesyal oswa yon moun ou renmen.","c3.list":"<li>Foto, souvni ak istwa</li><li>Lèt ak mesaj pèsonèl</li><li>Yon design fèt pou okazyon an</li>",
  "about.eye":"MOUN KI DÈYÈ PIXELS YO","about.title":"Hey, mwen se Rolph.<br><em>Ann fè l pou ou.</em>","about.p1":"Mwen te kòmanse kreye sit entènèt pou bay lide lavi, ladan yo te gen yon kado pèsonèl pou yon moun espesyal. Kounye a, m ap bati Rolph Studio pou ede moun mete istwa yo ak biznis yo sou entènèt.","about.p2":"Ou pote lide a, foto yo ak detay yo. Mwen ede w transfòme yo an yon sit ki klè, pèsonèl e fasil pou itilize.","about.lang":"Nou ka pale an anglè, fransè oswa kreyòl ayisyen.",
  "steps.eye":"KIJAN N AP TRAVAY ANSANM","steps.title":"Soti nan “mwen gen yon lide”<br>rive nan “sa se sit pa m.”","s1.label":"KONVÈSASYON AN","s1.title":"Di m sa w ap imajine.","s1.p":"N ap pale sou moun ou vle touche yo, objektif sit la ak kontni ou deja genyen.","s2.label":"PREMYE APÈSI A","s2.title":"Gade lide ou pran fòm.","s2.p":"Mwen prepare yon design pou ou revize. N ap ajiste l selon sa nou te dakò sou li.","s3.label":"LIVREZON AN","s3.title":"Pare pou pataje l.","s3.p":"N ap verifye dènye detay yo epi dakò sou hosting, domain ak fason mizajou yo ap fèt pita.",
  "faq.eye":"KÈK BAGAY POU KONNEN","faq.title":"Anvan nou<br>kòmanse.","q1":"Konbyen yon sit entènèt koute?","a1":"Chak pwojè diferan. N ap dakò sou sa pwojè a gen ladan l, paj yo, fonksyon yo, pri a ak delè a anvan travay la kòmanse.","q2":"Kisa mwen bezwen bay?","a2":"Lide ou, detay sou biznis oswa pwojè a, tèks, foto, lyen ak nenpòt lòt bagay ou vle mete ladan l.","q3":"Èske ou ka konekte paj rezèvasyon mwen an?","a3":"Wi. Nou ka mete lyen rezèvasyon ak kontak ou deja genyen dirèkteman sou sit la.","q4":"Èske mwen ka mande chanjman pita?","a4":"Nou ka pale sou mizajou nan lavni ak fason ou vle antreteni sit la apre livrezon.",
  "contact.eye":"LIDE OU KÒMANSE ISIT","contact.title":"Ann kreye<br><em>yon bagay pou ou.</em>","contact.p":"Di m sa w ap kreye, pou kiyès li ye, ak kilè ou ta renmen li pare.","contact.ready":"Pare pou kòmanse yon pwojè?","contact.reply":"Di m sa w ap kreye epi m ap reponn ou.","contact.email":"Voye imèl ↗","contact.call":"Rele m ↗","contact.text":"Voye mesaj ↗","footer":"© 2026 Rolph Studio · Vizyon pa w. Sit entènèt pa w.","footer.work":"Gade pwojè yo ↗"
 }
};

const map=[
 ['.hero .eyebrow','eyebrow.hero'],['.hero h1','hero.title'],['.hero-bottom>p','hero.lead'],['.hero-copy>p','hero.copy'],['.actions .primary','hero.work'],['.actions .ghost','hero.plan'],['.ticker span:nth-of-type(1)','ticker.business'],['.ticker span:nth-of-type(2)','ticker.personal'],['.ticker span:nth-of-type(3)','ticker.gifts'],['.ticker small','ticker.small'],
 ['#work .eyebrow','work.eye'],['#work .section-head h2','work.title'],['#work .section-head p','work.desc'],['.project-info>div:last-child>span','work.explore'],['.project-info>div:last-child>p','work.meta'],
 ['#services>.eyebrow','services.eye'],['#services .section-head h2','services.title'],['#services .section-head p','services.desc'],
 ['.cards article:nth-child(1)>span','c1.label'],['.cards article:nth-child(1)>h3','c1.title'],['.cards article:nth-child(1)>p','c1.p'],['.cards article:nth-child(1)>ul','c1.list'],['.cards article:nth-child(2)>span','c2.label'],['.cards article:nth-child(2)>h3','c2.title'],['.cards article:nth-child(2)>p','c2.p'],['.cards article:nth-child(2)>ul','c2.list'],['.cards article:nth-child(3)>span','c3.label'],['.cards article:nth-child(3)>h3','c3.title'],['.cards article:nth-child(3)>p','c3.p'],['.cards article:nth-child(3)>ul','c3.list'],
 ['.blue .eyebrow','about.eye'],['.blue h2','about.title'],['.about>div:last-child>p:nth-child(1)','about.p1'],['.about>div:last-child>p:nth-child(2)','about.p2'],['.about .lang','about.lang'],
 ['.steps~*','unused']
];
const extraMap=[
 ['section.section.wrap:not(#services)>.eyebrow','steps.eye'],['section.section.wrap:not(#services)>.section-head h2','steps.title'],['.steps article:nth-child(1)>span','s1.label'],['.steps article:nth-child(1)>h3','s1.title'],['.steps article:nth-child(1)>p','s1.p'],['.steps article:nth-child(2)>span','s2.label'],['.steps article:nth-child(2)>h3','s2.title'],['.steps article:nth-child(2)>p','s2.p'],['.steps article:nth-child(3)>span','s3.label'],['.steps article:nth-child(3)>h3','s3.title'],['.steps article:nth-child(3)>p','s3.p'],
 ['.faq .eyebrow','faq.eye'],['.faq h2','faq.title'],['.accordion details:nth-child(1) summary','q1'],['.accordion details:nth-child(1) p','a1'],['.accordion details:nth-child(2) summary','q2'],['.accordion details:nth-child(2) p','a2'],['.accordion details:nth-child(3) summary','q3'],['.accordion details:nth-child(3) p','a3'],['.accordion details:nth-child(4) summary','q4'],['.accordion details:nth-child(4) p','a4'],
 ['#contact .eyebrow','contact.eye'],['#contact h2','contact.title'],['#contact>.wrap>p','contact.p'],['.contact-options>strong','contact.ready'],['.contact-options>span','contact.reply'],['.contact-buttons a:nth-child(1)','contact.email'],['.contact-buttons a:nth-child(2)','contact.call'],['.contact-buttons a:nth-child(3)','contact.text'],['.footer p','footer'],['.footer>a:last-child','footer.work']
];
function setText(selector,key,lang){const el=document.querySelector(selector);if(!el||!translations[lang][key])return;let html=translations[lang][key];if(el.tagName==='SUMMARY'){const plus=el.querySelector('span');el.childNodes[0].textContent=html; if(plus) el.appendChild(plus);}else el.innerHTML=html;}
function applyLanguage(lang){if(!translations[lang])lang='en';document.documentElement.lang=lang==='ht'?'ht':lang;document.querySelector('[data-i18n="nav.work"]').textContent=translations[lang]['nav.work'];document.querySelector('[data-i18n="nav.services"]').textContent=translations[lang]['nav.services'];document.querySelector('[data-i18n="nav.talk"]').textContent=translations[lang]['nav.talk'];[...map,...extraMap].forEach(([s,k])=>k!=='unused'&&setText(s,k,lang));const labels={en:'EN ▾',fr:'FR ▾',ht:'KR ▾'};document.querySelector('.language-button').textContent=labels[lang];localStorage.setItem('rolph-language',lang);}
const picker=document.querySelector('.language-picker'),langButton=document.querySelector('.language-button');
langButton?.addEventListener('click',e=>{e.stopPropagation();picker.classList.toggle('open');langButton.setAttribute('aria-expanded',picker.classList.contains('open'));});
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{applyLanguage(b.dataset.lang);picker.classList.remove('open');langButton.setAttribute('aria-expanded','false');}));
document.addEventListener('click',()=>{picker?.classList.remove('open');langButton?.setAttribute('aria-expanded','false');});
applyLanguage(localStorage.getItem('rolph-language')||'en');
